export const products = [
  {
    id: 1,
    name: "Product 1",
    price: 40,
    description: "This is a product description.",
    image: "https://placehold.co/600x400/png",
    stock: 10,
  },
  {
    id: 2,
    name: "Product 2",
    price: 50,
    description: "This is another product description.",
    image: "https://placehold.co/600x400/png",
    stock: 5,
  },
  {
    id: 3,
    name: "Product 3",
    price: 60,
    description: "This is yet another product description.",
    image: "https://placehold.co/600x400/png",
    stock: 3,
  },
  {
    id: 4,
    name: "Product 4",
    price: 70,
    description: "This is yet another product description.",
    image: "https://placehold.co/600x400/png",
    stock: 2,
  },
  {
    id: 5,
    name: "Product 5",
    price: 80,
    description: "This is yet another product description.",
    image: "https://placehold.co/600x400/png",
    stock: 1,
  },
  {
    id: 6,
    name: "Product 6",
    price: 90,
    description: "This is yet another product description.",
    image: "https://placehold.co/600x400/png",
    stock: 8,
  },
  {
    id: 7,
    name: "Product 7",
    price: 100,
    description: "This is yet another product description.",
    image: "https://placehold.co/600x400/png",
    stock: 7,
  },
  {
    id: 8,
    name: "Product 8",
    price: 110,
    description: "This is yet another product description.",
    image: "https://placehold.co/600x400/png",
    stock: 6,
  },
  {
    id: 9,
    name: "Product 9",
    price: 120,
    description: "This is yet another product description.",
    image: "https://placehold.co/600x400/png",
    stock: 4,
  },
  {
    id: 10,
    name: "Product 10",
    price: 130,
    description: "This is yet another product description.",
    image: "https://placehold.co/600x400/png",
    stock: 9,
  },
  {
    id: 11,
    name: "Product 11",
    price: 140,
    description: "This is yet another product description.",
    image: "https://placehold.co/600x400/png",
    stock: 10,
  },
  {
    id: 12,
    name: "Product 12",
    price: 150,
    description: "This is yet another product description.",
    image: "https://placehold.co/600x400/png",
    stock: 15,
  },
  {
    id: 13,
    name: "Product 13",
    price: 160,
    description: "This is yet another product description.",
    image: "https://placehold.co/600x400/png",
    stock: 8,
  },
];
