export const products = [
  {
    id: 1,
    name: "Product 1",
    price: 40,
    description: "This is a product description.",
    image: "https://via.placeholder.com/150",
    stock: 10,
  },
  {
    id: 2,
    name: "Product 2",
    price: 50,
    description: "This is another product description.",
    image: "https://via.placeholder.com/150",
    stock: 5,
  },
  {
    id: 3,
    name: "Product 3",
    price: 60,
    description: "This is yet another product description.",
    image: "https://via.placeholder.com/150",
    stock: 3,
  },
  {
    id: 4,
    name: "Product 4",
    price: 70,
    description: "This is yet another product description.",
    image: "https://via.placeholder.com/150",
    stock: 2,
  },
  {
    id: 5,
    name: "Product 5",
    price: 80,
    description: "This is yet another product description.",
    image: "https://via.placeholder.com/150",
    stock: 1,
  },
  {
    id: 6,
    name: "Product 6",
    price: 90,
    description: "This is yet another product description.",
    image: "https://via.placeholder.com/150",
    stock: 8,
  },
];
